DROP VIEW IF EXISTS vw_partida_placar;
DROP VIEW IF EXISTS vw_gol_detalhado;

DROP TABLE IF EXISTS gol;
DROP TABLE IF EXISTS partida;
DROP TABLE IF EXISTS elenco;
DROP TABLE IF EXISTS inscricao_time;
DROP TABLE IF EXISTS estadio;
DROP TABLE IF EXISTS jogador;
DROP TABLE IF EXISTS time;
DROP TABLE IF EXISTS campeonato;
DROP TABLE IF EXISTS usuario;
